# ===============================
# = DATASOURCE
# ===============================

## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring.datasource.url=jdbc:postgresql://104.199.61.170:5432/postgres
spring.datasource.username= postgres
spring.datasource.password= Cloud5231!
## Other DATASOURCE Configs
spring.jpa.database=POSTGRESQL
spring.database.driverClassName=org.postgresql.Driver
spring.datasource.test-while-idle=true
spring.datasource.test-on-borrow=true
spring.datasource.test-on-return=false
spring.datasource.validation-interval=30000
spring.datasource.validation-query=SELECT 1
spring.datasource.time-between-eviction-runs-millis=5000
spring.datasource.min-evictable-idle-time-millis=5000
spring.datasource.remove-abandoned=true
spring.datasource.remove-abandoned-timeout=60

spring.datasource.tomcat.test-while-idle=true
spring.datasource.initialization-mode=always
# spring.datasource.data=data.sql
spring.datasource.continue-on-error=true
spring.datasource.platform=postgres

spring.datasource.hikari.max-lifetime=45000
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=35000


# ===============================
# = JPA HIBERNATE
# ===============================

# The SQL dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQL10Dialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
# Hibernate ddl auto (create, create-drop, validate, update)
# spring.jpa.hibernate.ddl-auto = update
spring.jpa.hibernate.ddl-auto = validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.globally_quoted_identifiers=true
hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.naming.physical-strategy=org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

spring.jpa.properties.hibernate.jdbc.time_zone=GMT+3
