/**
 * GET EPICS
 */

export const GET_EPICS_REQUEST = "GET_EPICS_REQUEST";
export const GET_EPICS_SUCCESS = "GET_EPICS_SUCCESS";

/**
 * CREATE EPIC
 */

export const CREATE_EPIC_REQUEST = "CREATE_EPIC_REQUEST";
export const CREATE_EPIC_SUCCESS = "CREATE_EPIC_SUCCESS";

/**
 * GET EPIC BY ID
 */

export const GET_EPIC_BY_ID_REQUEST = "GET_EPIC_BY_ID_REQUEST";
export const GET_EPIC_BY_ID_SUCCESS = "GET_EPIC_BY_ID_SUCCESS";

/**
 * UPDATE EPIC
 */

export const UPDATE_EPIC_REQUEST = "UPDATE_EPIC_REQUEST";
export const UPDATE_EPIC_SUCCESS = "UPDATE_EPIC_SUCCESS";
